import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Link from "next/link";
import style from "@/styles/layout.module.css";
import { ReactNode } from "react";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const RootLayout = ({ children }: { children: ReactNode }) => {
  return (
    <html lang="ko">
      <body className={style.container}>
        <div>
          <header>
            <Link href={"/"}>Park Phillips</Link>
            <main>{children}</main>
            <footer>제작 @Park Phillips</footer>
          </header>
        </div>
      </body>
    </html>
  );
};

export default RootLayout;
