import type { Metadata } from "next";
import Link from "next/link";
import style from "@/styles/layout.module.css";
import { ReactNode } from "react";
import { IBookData } from "@/types";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const Footer = async () => {
  const response = await fetch(
    `${process.env.NEXT_PUBLIC_API_SERVER_URL}/book`
  );
  if (!response.ok) {
    return <footer>제작 @Park Phillips</footer>;
  }

  const books: IBookData[] = await response.json();
  const bookCount = books.length;
  return (
    <footer>
      <div>제작 @Park Phillips</div>
      <div>{bookCount}개의 도서가 등록되었습니다.</div>
    </footer>
  );
};

const RootLayout = ({ children }: { children: ReactNode }) => {
  return (
    <html lang="ko">
      <body className={style.container}>
        <div>
          <header>
            <Link href={"/"}>Park Phillips</Link>
            <main>{children}</main>
            <Footer />
          </header>
        </div>
      </body>
    </html>
  );
};

export default RootLayout;
